Team-Binions/Team-Binions

- src/main/java/com/beanions/common/dto/MembersDTO.java
- src/main/java/com/beanions/user/service/userServiceTemp.java
> test - develop branch

- src/main/java/com/beanions/common/controller/MainController.java
- src/main/resources/assets/css/default.css
- src/main/resources/assets/css/user/common.css
- src/main/resources/templates/user/main.html
> #37 
>  MAIN 페이지 레이아웃 추가 및 default.css 기본폰트 설정 추가
▼↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
>
> [FEATURE][MAIN]메인페이지 추가 및 mainController내 main페이지 연결 경로 수정 & default.css 기본폰트 설정 추가 

- src/main/resources/assets/css/user/main.css
- src/main/resources/templates/user/main.html
> [FEATURE][MAIN] 메인 페이지 HTML 수정 및 main.css 추가

- src/main/java/com/beanions/common/dao/user/NoticeMapper.java
- src/main/java/com/beanions/user/controller/NoticeController.java
- src/main/java/com/beanions/user/service/NoticeService.java
- src/main/resources/application.yml
- src/main/resources/mapper/NoticeMapper.xml
- src/main/resources/templates/user/modify.html
- src/main/resources/templates/user/noticeboard.html
- src/main/resources/templates/user/noticeboarddetail.html
> [FEATURE][BOARD]공지사항

- src/main/java/com/beanions/user/controller/board/FreeBoardController.java
> testcommit

- src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
- src/main/java/com/beanions/user/controller/board/FreeBoardController.java
- src/main/java/com/beanions/user/service/board/FreeBoardService.java
- src/main/resources/mapper/userBoard/FreeBoardMapper.xml
- src/main/resources/templates/user/board/freeboardmodify.html
- src/main/resources/templates/user/board/noticeboard.html
- src/main/resources/templates/user/board/noticeboarddetail.html
- src/main/resources/templates/user/board/postRegist.html
- src/main/resources/templates/user/board/yesinDetail.html
- src/main/resources/templates/user/board/yesinList.html
- src/main/resources/templates/user/layout/header.html
> [Feature][post]board등록 기능

- src/main/java/com/beanions/common/dao/user/MyPageMapper.java
- src/main/java/com/beanions/common/dto/MyPageDTO.java
- src/main/java/com/beanions/user/controller/MyPageController.java
- src/main/java/com/beanions/user/service/MyPageService.java
- src/main/resources/assets/css/user/mypage.css
- src/main/resources/mapper/MyPageMapper.xml
- src/main/resources/templates/user/mypage/mypageComment.html
- src/main/resources/templates/user/mypage/mypageFree.html
- src/main/resources/templates/user/mypage/mypageMain.html
- src/main/resources/templates/user/mypage/mypageReview.html
> [FEATURE][MYPAGE] 마이페이지 레이아웃 및 기능 작업

- src/main/java/com/beanions/common/controller/MainController.java
- src/main/java/com/beanions/common/controller/SignupController.java
- src/main/java/com/beanions/common/dao/signup/SignupMapper.java
- src/main/java/com/beanions/common/dto/MembersDTO.java
- src/main/java/com/beanions/common/service/SignupService.java
- src/main/resources/assets/css/user/signup.css
- src/main/resources/assets/js/signup.js
- src/main/resources/mapper/SignupMapper.xml
- src/main/resources/templates/user/login.html
- src/main/resources/templates/user/main.html
- src/main/resources/templates/user/signup.html
> ex) #29 
1. textarea태그 / 텍스트 크기 등 상세 디테일은 develop할 예정입니다.
2. 웨딩홀인증 파일명을 저장하기위해 String 자료형의 컬럼이 필요했습니다. 그래서 MembersDTO파일 필드 중 weddingVerified 값의 자료형을 Boolean >> String으로 변경했습니다. 관리자 차원에서 별도로 웨딩홀인증 파일에대한 인/허가를 할거라면 별도의 컬럼을 관리할 필요가 있습니다.
또, DTO 파일은 DB테이블 확립될때 까지 변경소요 있을 예정입니다. 유의해주세용
> 기존에 MembersDTO 관련한 작업을 진행하신분들은 해당 작업 내용 때문에 오류가 있을 수 있으니 유의 부탁드립니다 (boolean 자료형 값으로 가져오던게 String형으로 0/1 이런식으로 가져올 것 or 값을 주입 시킬때 true/false로 주입시키면 String형이 아니라서 자료형 오류 반환 / DB dml시 자료형이 맞지않아 값 저장이 안될 것임)
1. 유효성검사 내용 중 아래 스크린샷 내용 외에 자릿수 검사, 특수문자 검사, 띄어쓰기, 번호 형식 등 유효 값 체크 및 필수 항목 미입력시 가입 불가 처리
2. 필수 항목 미입력 후 가입 시도시, 미입력 된 항목으로 자동 스크롤링
3. 파일 업로드 항목은 가입 전 업로드를 확정한 순간 설정된 파일에 저장되며, 가입을 확정할때 한개의 파일만 업로드 가능하도록 조치 >> 정확히는 DB에 저장될때 가장 최근에 등록한 파일만 전송하도록 조치
> 업로드 후 가입을 취소할때 파일에 저장된 파일에 대한 관리 여부 검토 필요 ( 보관 or 폐기 처분)
1. …
> [FEATURE][SIGNUP]회원가입 기능

- src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
- src/main/java/com/beanions/common/dao/user/board/MagazineMapper.java
- src/main/java/com/beanions/user/controller/board/FreeBoardController.java
- src/main/java/com/beanions/user/controller/board/MagazineController.java
- src/main/java/com/beanions/user/service/board/FreeBoardService.java
- src/main/java/com/beanions/user/service/board/MagazineService.java
- src/main/resources/mapper/userBoard/FreeBoardMapper.xml
- src/main/resources/mapper/userBoard/MagazineMapper.xml
- src/main/resources/templates/user/board/magazineList.html
> [FEATURE][FREEMAGAZINEEUN]이름 수정

- src/main/java/com/beanions/common/dao/user/board/ReviewMapper.java
- src/main/java/com/beanions/user/controller/board/ReviewController.java
- src/main/java/com/beanions/user/service/board/NoticeService.java
- src/main/java/com/beanions/user/service/board/ReviewService.java
- src/main/resources/mapper/userBoard/ReviewMapper.xml
- src/main/resources/templates/user/board/reviewList.html
> [FEATURE][REVIEW] 리뷰 페이지 복제

- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeModify.html
> [FEATURE][BOARD] 보드 버튼 링크 수정

- src/main/java/com/beanions/common/dao/user/MyPageMapper.java
- src/main/java/com/beanions/common/dto/MembersDTO.java
- src/main/java/com/beanions/common/dto/MyPageDTO.java
- src/main/java/com/beanions/user/controller/MyPageController.java
- src/main/java/com/beanions/user/service/MyPageService.java
- src/main/resources/assets/css/user/mypage.css
- src/main/resources/mapper/MyPageMapper.xml
- src/main/resources/templates/user/mypage/mypageComment.html
- src/main/resources/templates/user/mypage/mypageFree.html
- src/main/resources/templates/user/mypage/mypageReview.html
> #61 
> 마이페이지 > 나의 글 메뉴(예리뷰/예수다/댓글) READ 기능 완료
> 예수다 게시글의 경우 클릭시, 해당 상세페이지로 링크 연결
등록 게시글이 여러 개일 경우, 자동 글 번호 no 적용 및 최신순으로 정렬
> [FEATURE][MYPAGE] - 마이페이지 > 나의 글 메뉴(예리뷰/예수다/댓글) READ 기능 완료

- src/main/resources/assets/css/admin/adminPost.css
- src/main/resources/assets/css/admin/common.css
- src/main/resources/templates/admin/header.html
- src/main/resources/templates/admin/magazine/detail.html
- src/main/resources/templates/admin/magazine/list.html
- src/main/resources/templates/admin/magazine/regist.html
- src/main/resources/templates/admin/magazine/update.html
- src/main/resources/templates/admin/main/dashBoard.html
- src/main/resources/templates/admin/notice/detail.html
- src/main/resources/templates/admin/notice/list.html
- src/main/resources/templates/admin/notice/regist.html
- src/main/resources/templates/admin/notice/update.html
- src/main/resources/templates/admin/post/detail.html
- src/main/resources/templates/admin/post/list.html
- src/main/resources/templates/admin/sidebar.html
> #26
> layout.html -> header.html, sidebar.html 분리
> common.css 수정
> 상세페이지 기본 css 적용
> 이슈 닫지 말아주세요!
> [FEATURE][ADMIN] 관리자 페이지 레이아웃 수정 및 상세페이지 기본 CSS 적용

- src/main/java/com/beanions/user/controller/board/FreeBoardController.java
- src/main/resources/mapper/userBoard/FreeBoardMapper.xml
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/freeModify.html
- src/main/resources/templates/user/board/freeRegist.html
- src/main/resources/templates/user/board/reviewList.html
> [FEATURE][EUN] 댓글 뷰, 자유 게시판 MODIFY연결 수정

- src/main/java/com/beanions/common/dao/user/board/ReviewMapper.java
- src/main/java/com/beanions/common/dto/PostAndMemberDTO.java
- src/main/java/com/beanions/user/controller/board/FreeBoardController.java
- src/main/java/com/beanions/user/controller/board/ReviewController.java
- src/main/java/com/beanions/user/service/board/ReviewService.java
- src/main/resources/mapper/userBoard/FreeBoardMapper.xml
- src/main/resources/mapper/userBoard/ReviewMapper.xml
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/reviewList.html
> 조회수 뷰 추가 되었고 리뷰를 freeList로 리다이렉트 함
>
> [FEATURE][EUN] 조회수 뷰 추가, 리뷰 매핑

- src/main/resources/mapper/userBoard/FreeBoardMapper.xml
- src/main/resources/mapper/userBoard/MagazineMapper.xml
- src/main/resources/mapper/userBoard/NoticeMapper.xml
- src/main/resources/mapper/userBoard/ReviewMapper.xml
- src/main/resources/templates/user/board/magazineDetail.html
- src/main/resources/templates/user/board/noticeDetail.html
> [FEATURE][BOARD] 상세페이지 닉네임 추가

- src/main/java/com/beanions/common/controller/SignupController.java
- src/main/java/com/beanions/common/service/SignupService.java
- src/main/resources/assets/css/user/signup.css
- src/main/resources/assets/js/signup.js
- src/main/resources/templates/user/signup.html
> ex) #79 
> #79
1. 닉네임 조건 수정 완료 : 영어+숫자 조건 제거
2. 회원가입/서버재시작 시간 로깅
3. CSS 정리/수정
> [FEATURE][SIGNUP] 회원가입 0513 피드백

- src/main/resources/assets/css/admin/common.css
- src/main/resources/templates/admin/magazine/detail.html
- src/main/resources/templates/admin/magazine/list.html
- src/main/resources/templates/admin/main/dashBoard.html
- src/main/resources/templates/admin/notice/detail.html
- src/main/resources/templates/admin/notice/list.html
- src/main/resources/templates/admin/post/list.html
- src/main/resources/templates/admin/sidebar.html
> #26
> 공지사항 및 매거진 관리 전페 조회 페에지, 상세페이지 CSS 적용
> [FEATURE][ADMIN] 관리자 공지사항 & 매거진 관리 전체조회 페이지, 상세페이지 CSS 수정

- src/main/java/com/beanions/common/controller/MainController.java
- src/main/resources/assets/css/user/mypage.css
- src/main/resources/templates/user/mypage/mypageComment.html
- src/main/resources/templates/user/mypage/mypageFree.html
- src/main/resources/templates/user/mypage/mypageMyinfo.html
- src/main/resources/templates/user/mypage/mypageReview.html
> ex) #61 
> 이미지 경로 추가
> 로그인 화면 확인 차 common>mainController 에 로그인 페이지 매핑 경로 추가했는데 지우셔도 무방합니다.
> [FEATURE][MYPAGE] MYINFO(회원 정보 수정) 페이지 및 관련 아이콘 이미지 경로 연결

- src/main/java/com/beanions/common/dao/user/board/FreeBoardMapper.java
- src/main/java/com/beanions/common/dao/user/board/MagazineMapper.java
- src/main/java/com/beanions/common/dao/user/board/ReviewMapper.java
- src/main/java/com/beanions/common/dto/Page.java
- src/main/java/com/beanions/common/dto/PageMaker.java
- src/main/java/com/beanions/common/dto/PostDTO.java
- src/main/java/com/beanions/user/controller/board/PageController.java
- src/main/java/com/beanions/user/service/board/FreeBoardService.java
- src/main/java/com/beanions/user/service/board/MagazineService.java
- src/main/java/com/beanions/user/service/board/ReviewService.java
- src/main/resources/assets/css/user/board/notice.css
- src/main/resources/mapper/userBoard/FreeBoardMapper.xml
- src/main/resources/mapper/userBoard/MagazineMapper.xml
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/magazineList.html
- src/main/resources/templates/user/board/noticeDetail.html
- src/main/resources/templates/user/board/noticeList.html
- src/main/resources/templates/user/board/reviewList.html
- src/main/resources/templates/user/board/reviewModify.html
> #97 #99
> 페이지네이션, 조회수 기능 추가
> 공지사항 CSS 추가
> [FEATURE][BOARD] 공지사항 CSS, 페이지네이션, 조회수 기능 추가

- build.gradle
- src/main/java/com/beanions/auth/controller/AuthController.java
- src/main/java/com/beanions/auth/model/AuthDetails.java
- src/main/java/com/beanions/auth/model/service/AuthService.java
- src/main/java/com/beanions/common/controller/LoginService.java
- src/main/java/com/beanions/common/controller/MainController.java
- src/main/java/com/beanions/common/controller/SignupController.java
- src/main/java/com/beanions/common/dao/user/UserMapper.java
- src/main/java/com/beanions/common/dto/LoginUserDTO.java
- src/main/java/com/beanions/common/service/SignupService.java
- src/main/java/com/beanions/config/SecurityConfig.java
- src/main/java/com/beanions/config/handler/AuthFailHandler.java
- src/main/java/com/beanions/config/handler/AuthSuccessHandler.java
- src/main/resources/assets/js/signup.js
- src/main/resources/mapper/SignupMapper.xml
- src/main/resources/mapper/UserMapper.xml
- src/main/resources/templates/auth/fail.html
- src/main/resources/templates/auth/login.html
- src/main/resources/templates/user/layout/header.html
- src/main/resources/templates/user/signup.html
> ex) #109 
> #109
1. 로그인하면서 권한을 조회할 때, 암호화된 번호를 조회하기때문에 기존에 사용한 DB 데이터로는 로그인이 되지 않습니다.
2. 여기서 암호화라는건 회원가입할 때 랜덤하게 주어지는 값이어서 임의로 넣은 값으로는 사용할수가 없습니다.
3. 기존의 DB 데이터를 사용한다고 로그인시 암호화 로직을 빼게되면 에러를 뱉습니다.
4. Spring Security 자체가 암호화를 기본으로 설정되어있기 때문에 그렇습니다.
1. 지금부터는 실제로 회원가입을 진행 한 후에 로그인해서 마이페이지, 글쓰기, 관리자페이지 접근 등 권한에 맞게 진행되야할것같습니다.
2. 관리자(ADMIN)은 회원가입 한 후에 DML 수정문으로 USER > ADMIN으로 값 변경 후에 작업 진행해주셔야합니다.
> [FEATURE][LOGIN] 로그인 기능

- src/main/java/com/beanions/admin/controller/AdminController.java
- src/main/java/com/beanions/admin/service/MemberService.java
- src/main/java/com/beanions/common/dao/admin/AdminMapper.java
- src/main/java/com/beanions/common/dto/MembersDTO.java
- src/main/resources/assets/css/admin/membersCss.css
- src/main/resources/mapper/AdminMapper.xml
- src/main/resources/templates/admin/member/membersDetail.html
- src/main/resources/templates/admin/member/membersList.html
- src/main/resources/templates/admin/member/membersModify.html
> [FEATUR][ADMINDELETEMEMBER] 수정 및 삭제 완료

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/java/com/beanions/admin/controller/AdminMainController.java
- src/main/java/com/beanions/admin/service/AdminService.java
- src/main/java/com/beanions/common/controller/MainController.java
- src/main/java/com/beanions/common/dao/admin/AdminMapper.java
- src/main/java/com/beanions/common/dto/AdminMainDTO.java
- src/main/resources/assets/css/admin/common.css
- src/main/resources/mapper/AdminMapper.xml
- src/main/resources/templates/admin/main/dashBoard.html
> #26, #107
> 관리자 메인(dashBoard) 기능 구현
> * 가입자 수, 게시물 수, 리뷰 수, 예신&예랑 수 조회
> * 최신 공지사항 5, 최신 매거진 5 조회
> MainController에 있던 /admin 도메인 getMapping 메소드를 새로 AdminMainController를 생성해서 옮기고
> 기존에 있던 AdminMainController 이름을 AdminBoardController로 변경 하였습니다.
> [FEATURE][ADMIN]관리자 dashBoard 기능 구현

- src/main/java/com/beanions/user/controller/board/FreeBoardController.java
- src/main/java/com/beanions/user/controller/board/MagazineController.java
- src/main/java/com/beanions/user/controller/board/NoticeController.java
- src/main/java/com/beanions/user/controller/board/ReviewController.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/magazine.css
- src/main/resources/assets/css/user/board/notice.css
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/freeModify.html
- src/main/resources/templates/user/board/freeRegist.html
- src/main/resources/templates/user/board/magazineDetail.html
- src/main/resources/templates/user/board/magazineList.html
- src/main/resources/templates/user/board/noticeDetail.html
- src/main/resources/templates/user/board/noticeList.html
- src/main/resources/templates/user/board/reviewDetail.html
- src/main/resources/templates/user/board/reviewList.html
- src/main/resources/templates/user/board/reviewModify.html
- src/main/resources/templates/user/layout/header.html
> #108 
>mapping 주소 /user 제거
> 게시판 CSS 추가
> 공지사항 메인 페이지 수정
> 매거진 상세페이지
> 자유게시판 메인페이지
> 자유게시판 상세페이지 (댓글 부분 수정 필요)
> 자유게시판 수정페이지
> 리뷰게시판 메인페이지
> 리뷰게시판 상세페이지
> 리뷰게시판 수정페이지
---
---
> 댓글과 사진파일 들어가는 부분과 글쓰기는 미구현
> [FEATURE][BOARD] 게시판 CSS, 맵핑 변경

- src/main/resources/assets/css/user/common.css
- src/main/resources/assets/images/common/icon_arrow_left_white.svg
- src/main/resources/assets/images/common/icon_arrow_right_white.svg
- src/main/resources/assets/js/common.js
- src/main/resources/templates/user/layout/footer.html
- src/main/resources/templates/user/layout/header.html
> ex) #114
> common.css 속성 및 아이콘 이미지 추가 & common.js 추가
>
> [FEATURE][COMMONSETTING] common.css 속성 및 아이콘 이미지 추가 & common.js 추가

- src/main/java/com/beanions/user/controller/MyPageController.java
- src/main/resources/assets/css/user/common.css
- src/main/resources/assets/images/common/icon_arrow_left_white.svg
- src/main/resources/assets/images/common/icon_arrow_right_white.svg
- src/main/resources/assets/js/common.js
- src/main/resources/templates/user/layout/footer.html
- src/main/resources/templates/user/layout/header.html
- src/main/resources/templates/user/mypage/fileUpload.html
>#118
> 파일 업로드시 미리보기 기능 및 레이아웃 작업
>
> [FEATURE][FILEUPLOAD] 파일 업로드시 미리보기 기능 및 레이아웃 작업

- src/main/java/com/beanions/board/common/dto/PostAndMemberDTO.java
- src/main/java/com/beanions/board/review/controller/ReviewController.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/notice.css
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/mapper/board/FreeBoardMapper.xml
- src/main/resources/mapper/board/ReviewMapper.xml
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/noticeList.html
- src/main/resources/templates/user/board/reviewDetail.html
- src/main/resources/templates/user/board/reviewList.html
> 조회수 기능 추가 및 CSS 수정
> 리뷰게시판 게시글 승인 여부에 따른 결과 표시
> 활성화 게시글만 리스트에 나올 수 있게 수정
>비활성화 게시글 X
---
---
---
> [FEATURE][BOARDSTATUS] 승인 여부, 활성화 여부에 따른 게시물 정보 수정

- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
- src/main/java/com/beanions/board/free/service/FreeBoardService.java
- src/main/java/com/beanions/common/dto/SearchDTO.java
- src/main/java/com/beanions/common/paging/PagingResponse.java
- src/main/java/com/beanions/config/SecurityConfig.java
- src/main/resources/mapper/board/FreeBoardMapper.xml
- src/main/resources/templates/user/board/freeList.html
> #124
> 페이지 네이션 기능 추가중 - 페이지 count 정보 불러오기 까지 가능
>
> [Feature][eun] 페이지 네이션 기능 추가중

- src/main/java/com/beanions/admin/controller/AdminController.java
- src/main/java/com/beanions/admin/dao/AdminMapper.java
- src/main/java/com/beanions/admin/service/AdminMemberService.java
- src/main/resources/assets/css/admin/adminPost.css
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/member/membersDetail.html
> ex) #123
> 이전에는 리스트 <MembersDTO> 도 같이 담아서 받아줬는데 리스트를 제거했고
> 쿼리문까지 작성하고 들어가면 이런식으로 500에러를 뱉음 리스트를 빼주고
> 이런식으로 변경해줌
>
> [FEATURE][ADMIN] 회원 상세 조회 이슈

- src/main/java/com/beanions/board/common/dto/PostAndMemberDTO.java
- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
- src/main/java/com/beanions/board/free/service/FreeBoardService.java
- src/main/java/com/beanions/board/review/controller/ReviewController.java
- src/main/java/com/beanions/common/dto/SearchDTO.java
- src/main/java/com/beanions/common/paging/PagingResponse.java
- src/main/java/com/beanions/config/SecurityConfig.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/notice.css
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/mapper/board/FreeBoardMapper.xml
- src/main/resources/mapper/board/ReviewMapper.xml
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/noticeList.html
- src/main/resources/templates/user/board/reviewDetail.html
- src/main/resources/templates/user/board/reviewList.html
> [Feature][board] 승인 여부, 활성화 여부에 따른 게시물 정보 수정, 페이지네이션 기능 추가

- src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
- src/main/resources/mapper/board/MagazineMapper.xml
- src/main/resources/templates/user/board/freeList.html
> [Feature][eun] 페이지네이션 구현중

- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/java/com/beanions/board/review/controller/ReviewController.java
- src/main/java/com/beanions/common/dto/SearchDTO.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/magazine.css
- src/main/resources/assets/css/user/board/notice.css
- src/main/resources/assets/css/user/board/regist.css
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/mapper/board/FreeBoardMapper.xml
- src/main/resources/mapper/board/ReviewMapper.xml
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/freeRegist.html
- src/main/resources/templates/user/board/noticeDetail.html
- src/main/resources/templates/user/board/noticeList.html
> #134 
> 게시판 LIST 기본 높이 설정
> 공지사항 아이콘 삽입
> notice detail 영역 설정 변경
---
> 리뷰 조회수 카운트
> 글쓰기 기능 수정
> 최신순 정렬 기능 수정
---
> [FEATURE][BOARD]글쓰기 기능, CSS 수정, 정렬 기능 수정

- src/main/resources/assets/css/user/common.css
- src/main/resources/templates/user/layout/header.html
> #140 
> 마이페이지 버튼 관련 common.css 속성 및 아이콘 이미지 추가
>
> [FEATURE][COMMONSETTING] 마이페이지 버튼 관련 common.css 속성 및 아이콘 이미지 추가

- src/main/java/com/beanions/mypage/controller/MyPageController.java
- src/main/java/com/beanions/mypage/dao/MyPageMapper.java
- src/main/java/com/beanions/mypage/dto/SchedulesDTO.java
- src/main/java/com/beanions/mypage/service/MyPageService.java
- src/main/java/com/beanions/user/controller/SignupController.java
- src/main/resources/assets/js/signup.js
- src/main/resources/mapper/mypage/MyPageMapper.xml
- src/main/resources/templates/user/mypage/mypageMyinfo.html
- src/main/resources/templates/user/mypage/mypageReview.html
> ex) #132 
1. 로그인 시 저장된 세션 정보 이용해서 마이페이지 바인딩
2. 회원가입 이메일 유효성 관련 작업 마무리
> [FEATURE][MYPAGESESSION] 마이페이지 세션 정보 + 의존성 NULL 이슈 해결

- src/main/java/com/beanions/admin/controller/AdminController.java
- src/main/java/com/beanions/admin/dao/AdminMapper.java
- src/main/java/com/beanions/admin/dto/AdminMemberPostDTO.java
- src/main/java/com/beanions/admin/service/AdminMemberService.java
- src/main/resources/assets/css/admin/membersCss.css
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/member/membersDetail.html
- src/main/resources/templates/admin/member/membersList.html
- src/main/resources/templates/admin/member/membersModify.html
> [FEATURE][ADMIN] 회원 상세 관리 css 추가

- src/main/java/com/beanions/config/SecurityConfig.java
- src/main/java/com/beanions/search/controller/SearchController.java
- src/main/java/com/beanions/search/dao/SearchMapper.java
- src/main/java/com/beanions/search/service/SearchService.java
- src/main/resources/assets/css/user/search.css
- src/main/resources/templates/user/search/result.html
> #130
> 검색 결과 페이지 관련 패키지, 디렉토리, 파일 생성
> [FEATURE][SEARCH]검색 결과 페이지 추가

- src/main/resources/templates/user/board/freeList.html
> [FEATURE][BOARD] 페이지네이션 기능 추가

- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/resources/assets/css/user/comment.css
- src/main/resources/templates/user/board/freeDetail.html
> [FEATURE][COMMENT] 게시글 상세페이지 내 댓글 레이아웃 및 스크립트 추가

- src/main/java/com/beanions/common/dto/SearchDTO.java
- src/main/java/com/beanions/search/controller/SearchController.java
- src/main/java/com/beanions/search/dao/SearchMapper.java
- src/main/java/com/beanions/search/service/SearchService.java
- src/main/resources/mapper/search/SearchMapper.xml
- src/main/resources/templates/user/main.html
- src/main/resources/templates/user/search/result.html
> #130 
> 메인페이지에서 검색 결과 페이지 연결
> 검색 유형에 따른 검색 기능 구현
* 메인페이지에서 검색시 '제목 + 내용' 결과
* 검색유형 : 제목
* 검색유형: 내용
> [FEATURE][SEARCH] 검색기능 초기 구현

- src/main/java/com/beanions/config/handler/GlobalExceptionHandler.java
- src/main/resources/application.yml
- src/main/resources/templates/error/403.html
- src/main/resources/templates/error/404.html
- src/main/resources/templates/error/500.html
- src/main/resources/templates/error/nullPointer.html
> [FEATURE][ERRORHANDLER] 에러페이지

- src/main/resources/assets/css/user/common.css
> #144 
> HEADER 서브 메뉴 관련 마우스 오버시 비정상적 활성화되는 버그 해결
>
> [FEATURE][COMMONSETTING] HEADER 서브 메뉴 관련 마우스 오버시 비정상적 활성화되는 버그 해결

- src/main/java/com/beanions/auth/controller/AuthController.java
- src/main/java/com/beanions/config/SecurityConfig.java
- src/main/java/com/beanions/config/handler/AuthFailHandler.java
- src/main/java/com/beanions/main/controller/MainController.java
- src/main/java/com/beanions/user/dto/EmailDTO.java
- src/main/java/com/beanions/user/service/MailService.java
- src/main/resources/assets/js/forgetInfo.js
- src/main/resources/assets/js/main.js
- src/main/resources/templates/auth/login.html
- src/main/resources/templates/user/main.html
#159
1. Spring boot Mail 기능 중 MimeMessage 객체의 사용 원칙으로 메일을 보내는 계정에 대한 인증이 꼭 필요하다.
2. 본 버전에서 설정된 계정은 본인 개인 계정이며 발신하는 계정도 우리 계정, 수신하는 계정도 우리 계정이다.
3. 유저가 본인의 이메일과 문의내용을 보내게 되면 메일과 문의 내용이 포함된 메일이 우리 메일주소로 전송된다.
(선택)
CSS 도움이 절실합니다.
> [FEATURE][INQUIRY] 문의 메일

- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
- src/main/java/com/beanions/board/free/service/FreeBoardService.java
- src/main/java/com/beanions/board/magazine/controller/MagazineController.java
- src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
- src/main/java/com/beanions/board/magazine/service/MagazineService.java
- src/main/java/com/beanions/board/notice/controller/NoticeController.java
- src/main/java/com/beanions/board/notice/dao/NoticeMapper.java
- src/main/java/com/beanions/board/notice/service/NoticeService.java
- src/main/java/com/beanions/board/review/controller/ReviewController.java
- src/main/java/com/beanions/board/review/dao/ReviewMapper.java
- src/main/java/com/beanions/board/review/service/ReviewService.java
- src/main/resources/mapper/board/FreeBoardMapper.xml
- src/main/resources/mapper/board/MagazineMapper.xml
- src/main/resources/mapper/board/NoticeMapper.xml
- src/main/resources/mapper/board/ReviewMapper.xml
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/magazineDetail.html
- src/main/resources/templates/user/board/magazineList.html
- src/main/resources/templates/user/board/noticeList.html
- src/main/resources/templates/user/board/reviewList.html
> #156
> 페이지네이션 게시판에 이식
> 매거진 상세 목록 오류 수정
>
> [Feature][pagination] 페이지네이션 게시판에 이식, 매거진 상세 목록 오류 수정

- src/main/java/com/beanions/admin/dto/AdminMainDTO.java
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/main/dashBoard.html
#170
> 관리자 Dashboard 방문자 수 조회 기능 추가
> 총 방문자 수, 오늘 방문자 수
> [FEATURE][ADMIN] 관리자 Dashboard 방문자 수 조회 기능 추가

- src/main/resources/templates/user/mypage/mypageMain.html
> #61
> 마이페이지 내 header 서브메뉴 작동 안하는 것 수정 - common.js 활성화 시킴(기존에 주석처림해놓은 상태)
>
> [FEATURE][MYPAGESESSION] 마이페이지 HEADER 수정

- src/main/java/com/beanions/board/common/dto/PostAndFilesDTO.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/magazine.css
- src/main/resources/templates/user/board/magazineList.html
> #168 
> magazine list css
작업하는 중입니다..
> [FEATURE][MAGAZINE] 매거진 LIST CSS

- src/main/resources/assets/js/signup.js
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/signup.html
#158 
1. 댓글 css 이슈 해결 feat.남지혜님
2. 회원가입 헤더 애니메이션 이슈 해결
> [FEATURE][COMMENT] 댓글 기능 추가 작업

- src/main/resources/assets/js/comment.js
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/magazineDetail.html
- src/main/resources/templates/user/board/noticeDetail.html
- src/main/resources/templates/user/board/reviewDetail.html
- src/main/resources/templates/user/signup.html
1. 공지사항 & 매거진에는 댓글 기능 추가 X
2. 예리뷰 카테고리에만 댓글 기능 추가 O
3. 헤더 애니메이션 적용 CSS 정상 적용
1. 게시글 상세 조회 css 통합해주세요
2. 댓글부분은 안건드리셔도됩니다.
3. 게시글 아무나 삭제 수정할수 있는거 해결해주세요. >> thymeleaf로 값 전달받을때 권한이랑 같이 Map<String,Object> 값으로 리턴받아서 전달할 수 있어요. 로그인한 권한에 맞게 관리하는거 comment.js > 댓글조회 부분이랑 FreeBoardController쪽에 구현되어 있으니 참고해보세요
> [FEATURE][COMMENTCOPY] 댓글 기능 타 게시글에 옯기기 작업

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/java/com/beanions/admin/dao/AdminMapper.java
- src/main/java/com/beanions/admin/service/AdminService.java
- src/main/resources/assets/css/admin/adminPost.css
- src/main/resources/assets/css/admin/common.css
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/footer.html
- src/main/resources/templates/admin/header.html
- src/main/resources/templates/admin/magazine/detail.html
- src/main/resources/templates/admin/magazine/regist.html
- src/main/resources/templates/admin/magazine/update.html
- src/main/resources/templates/admin/main/dashBoard.html
- src/main/resources/templates/admin/member/membersList.html
- src/main/resources/templates/admin/notice/detail.html
- src/main/resources/templates/admin/notice/regist.html
- src/main/resources/templates/admin/notice/update.html
- src/main/resources/templates/admin/post/detail.html
- src/main/resources/templates/admin/post/list.html
> #130
* 관리자 게시물 상세페이지 글 내용 영역 벗어나는 이슈 해결
* 버튼 hover style 변경 
* 회원관리 리스트 테이블 컬럼 간격 수정 
* 회원관리 회원번호 -> 번호로 게시물 관리 쪽과 통일 
* header 밑줄이나 사이드바 오른쪽 줄 색 통일 
* 게시물 상세조회 페이지 category text 부분 위치 조정 
* 관리자 dashboard 최신 빼기 ( 공지사항, 매거진 만 남게) 
* 관리자 dashboard 공지사항 조회수 영역 조정( 옆에 있는 매거진이랑 다름) 
* 활성화, 승인 => 모달 추가
* 모달창 아래부분 높이 조정 
* header logo에 메인페이지 연결 
* 게시판 관리 리스트 페이지에 검색 기능 추가(제목, 내용, 작성자)
> 푸터....
> [FEATURE][ADMIN] 관리자 페이지 전체적으로 수정 및 게시판 관리 리스트 페이지에 검색 기능 추가

- src/main/java/com/beanions/admin/controller/AdminController.java
- src/main/java/com/beanions/config/WebConfig.java
- src/main/resources/application.yml
- src/main/resources/assets/css/admin/membersCss.css
- src/main/resources/assets/js/signup.js
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/member/membersDetail.html
- src/main/resources/templates/admin/member/membersModify.html
#179 
1. 회원 조회 시 파일가져와 출력
2. 개발툴 활성화시켜서 폴더 업데이트 진행해야지만 파일이 깨지지 않고 가져오는 이슈 해결
3. 회원가입 유효성 이슈 보완
4. yml 정적 리소스 절대 경로 추가
> [FEATURE][ADMIN] 회원 상세 조회&수정 보완

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/java/com/beanions/admin/dao/AdminMapper.java
- src/main/java/com/beanions/admin/service/AdminService.java
- src/main/resources/assets/css/admin/common.css
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/notice/detail.html
- src/main/resources/templates/admin/notice/list.html
- src/main/resources/templates/admin/post/list.html
> #130,
> textarea에서 등록된 게시글 -> 조회시 개행 적용
> 공지사항 관리 페이지 검색 기능 추가
> [FEATURE][ADMIN] postContext 개행 적용 및 공지사항 관리 페이지 검색 기능 추가

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/resources/assets/css/admin/adminPost.css
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/magazine/detail.html
- src/main/resources/templates/admin/notice/regist.html
- src/main/resources/templates/admin/notice/update.html
- src/main/resources/templates/admin/post/detail.html
> [FEATURE][ADMIN] 관리자 페이지 상세 페이지 개행 적용

- src/main/resources/assets/css/admin/adminPost.css
- src/main/resources/assets/css/admin/common.css
- src/main/resources/templates/admin/notice/regist.html
- src/main/resources/templates/admin/notice/update.html
> [FEATURE][ADMIN] 공지사항 관리 등록, 수정 시 제목&내용 글자수 제한 추가

- docker-compose.yml
- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/java/com/beanions/board/review/controller/ReviewController.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/magazine.css
- src/main/resources/assets/css/user/board/notice.css
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/assets/css/user/writeBoard.css
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/reviewDetail.html
- src/main/resources/templates/user/mypage/fileUpload.html
- src/main/resources/templates/user/mypage/mypageReview.html
- src/main/resources/templates/user/mypage/mypageScheduleRegister.html
- start.sh
> #202
>  업로드 파일 fileupload.html 및 게시물 상세 페이지 레이아웃 수정 
>
> [FEATURE][UPLOADFILE_MODIFIED] 업로드 파일 fileupload.html 및 게시물 상세 페이지 레이아웃 수정 

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/java/com/beanions/admin/dto/AdminPostDTO.java
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/magazine/detail.html
- src/main/resources/templates/admin/post/detail.html
- src/main/resources/templates/user/signup.html
> [FEATURE][ADMINDETAILFILE] 관리자 상세 페이지 이미지 출력

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/java/com/beanions/board/free/dao/FreeBoardMapper.java
- src/main/java/com/beanions/board/free/service/FreeBoardService.java
- src/main/java/com/beanions/board/magazine/controller/MagazineController.java
- src/main/java/com/beanions/board/magazine/dao/MagazineMapper.java
- src/main/java/com/beanions/board/magazine/service/MagazineService.java
- src/main/java/com/beanions/board/notice/controller/NoticeController.java
- src/main/java/com/beanions/board/notice/dao/NoticeMapper.java
- src/main/java/com/beanions/board/notice/service/NoticeService.java
- src/main/java/com/beanions/board/review/controller/ReviewController.java
- src/main/java/com/beanions/board/review/dao/ReviewMapper.java
- src/main/java/com/beanions/board/review/service/ReviewService.java
- src/main/resources/assets/css/admin/common.css
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/magazine/detail.html
- src/main/resources/templates/admin/magazine/list.html
- src/main/resources/templates/admin/magazine/regist.html
- src/main/resources/templates/admin/magazine/update.html
- src/main/resources/templates/admin/member/membersList.html
- src/main/resources/templates/admin/notice/detail.html
- src/main/resources/templates/admin/notice/regist.html
- src/main/resources/templates/admin/notice/update.html
- src/main/resources/templates/admin/post/detail.html
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/magazineDetail.html
- src/main/resources/templates/user/board/noticeDetail.html
> [FEATURE][BOARD] 게시물 상세조회 페이지 개행 적용

- src/main/resources/templates/user/mypage/mypageComment.html
> #61
> 마이페이지에서 등록한 댓글 목록 확인 후 해당 댓글 있는 상세페이지 링크 연결
>
> [FEATURE][MYPAGE] 마이페이지 댓글 페이지에서 상세페이지 연결

- src/main/java/com/beanions/mypage/controller/MyPageController.java
- src/main/java/com/beanions/mypage/dao/MyPageMapper.java
- src/main/java/com/beanions/mypage/service/MyPageService.java
- src/main/resources/assets/js/comment.js
- src/main/resources/assets/js/mypage.js
- src/main/resources/mapper/mypage/MyPageMapper.xml
- src/main/resources/templates/user/mypage/mypageMyinfo.html
#213 
1. 내 정보 수정
2. 비밀번호 변경 안누르면 기존 비밀번호와 함께 전달
3. 변경 누르면 유효성 검사 진입
4. 모든 유효성 검사 통과 시 수정 완료
5. 이미지 출력
6. 이미지 수정
> [FEATURE][MYPAGE/MYINFO] 마이페이지 내 정보 수정

- src/main/resources/assets/css/user/board/free.css
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/freeModify.html
> [FEATURE][MODAL] 모달창

- src/main/java/com/beanions/admin/controller/AdminController.java
- src/main/java/com/beanions/admin/dao/AdminMapper.java
- src/main/java/com/beanions/admin/service/AdminMemberService.java
- src/main/resources/mapper/admin/AdminMapper.xml
- src/main/resources/templates/admin/member/membersList.html
> ex) #215
> 회원 상세 검색을 닉네임에 한글자라도 일치하면 나옵니다.
>
> [FEATURE][ADMIN] 회원 상세 검색

- src/main/resources/assets/css/user/mypage.css
- src/main/resources/assets/js/signup.js
- src/main/resources/templates/auth/fail.html
- src/main/resources/templates/user/signup.html
1. fetch문과 css적용 동시 적용 시 시간차때문인지 적용이 안되어 출력되는 현상
2. 로그인 요청 url 수정
> ## 회원가입/로그인 오류 수정

- src/main/java/com/beanions/board/free/controller/FreeBoardController.java
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/templates/user/board/freeModify.html
- src/main/resources/templates/user/board/freeRegist.html
- src/main/resources/templates/user/board/reviewList.html
- src/main/resources/templates/user/board/reviewModify.html
> REVIEW 수정 모달창
> PostMapping 주소 변경
> 헤더 common.js 변경
---
---
---
---
> [FEATURE][BOARDEDIT] REVIEW 수정 모달창, PostMapping 주소 변경, 헤더 common.js 변경

- src/main/resources/templates/admin/member/membersDetail.html
> ex) #230
> 상세관리 게시판부분 수정했습니다
>
> [FEATURE][ADMIN] 회원 상세 조회 페이지 수정

- src/main/java/com/beanions/admin/controller/AdminBoardController.java
- src/main/resources/assets/css/admin/adminWriteBoard.css
- src/main/resources/assets/js/adminFileUpload.js
- src/main/resources/mapper/mypage/UploadMapper.xml
- src/main/resources/templates/admin/magazine/regist.html
- src/main/resources/templates/admin/magazine/update.html
- src/main/resources/templates/user/board/reviewDetail.html
> #228
> 관리자 매거진 등록 레이아웃 수정
> 관리자 매거진 수정 레이아웃 수정
> 사용자 리뷰 상세페이지 접근 시 500 ERROR 해결 ( 글쓰기 등록 쿼리문 수정 - 이슈 확인 요망)
> [FEATURE][ADMIN&REVIEW] 관리자 매거진 기능 수정 및 리뷰페이지 이슈 해결

- src/main/java/com/beanions/mypage/controller/MyPageController.java
- src/main/java/com/beanions/mypage/dao/MyPageMapper.java
- src/main/java/com/beanions/mypage/service/MyPageService.java
- src/main/resources/assets/css/user/board/free.css
- src/main/resources/assets/css/user/board/review.css
- src/main/resources/assets/css/user/mypage.css
- src/main/resources/assets/js/mypage.js
- src/main/resources/mapper/mypage/MyPageMapper.xml
- src/main/resources/templates/user/board/freeDetail.html
- src/main/resources/templates/user/board/freeList.html
- src/main/resources/templates/user/board/reviewDetail.html
- src/main/resources/templates/user/layout/privacy.html
- src/main/resources/templates/user/layout/terms.html
- src/main/resources/templates/user/mypage/mypageComment.html
- src/main/resources/templates/user/mypage/mypageFree.html
- src/main/resources/templates/user/mypage/mypageMyinfo.html
- src/main/resources/templates/user/mypage/mypageReview.html
> 
> 마이페이지 > 회원정보수정 - 회원탈퇴 적용/게시판 상세 페이지 내 모달 위치 수정
>
> [FEATURE][MYPAGE/MYINFO] 마이페이지 > 회원정보수정 - 회원탈퇴 적용/게시판 상세 페이지 내 모달 위치 수정 

- src/main/resources/assets/css/user/common.css
- src/main/resources/templates/user/layout/about.html
> modify about context
